### ISSUE TITLE
Odd menu item overlap

### ISSUE THREAD

**Issue by rhubarbselleven** [govau/design-system-components#573]
![Example overlap](https://user-images.githubusercontent.com/1232550/49856248-71c80d00-fe43-11e8-8832-82a3527596ee.png)

Using: `Chrome Version 71.0.3578.80 (Official Build) (64-bit)`

**Comment by rhubarbselleven** [comment]
Hey @alex-page, It’s not keyboard and mouse but odd active and hover states when the list items are anchors with no real href. 

If they had a real location, we wouldn’t see this state

**Comment by alex-page** [comment]
Thanks for the information. We will take a look in the next sprint!

**Comment by alex-page** [comment]
@rhubarbselleven I am investigating this issue. I am using the https://govau.github.io/uikit-starter/form/ website as it mimics the markup you have described above.

I am a bit confused on how to repeat the issue. How I am trying:
- The "Form" menu item is active
- I move focus to the "Simple terms" menu item
- I click "Distinct from eachother" and the focus moves to that item?

- The "Form" menu item is active
- I click "Distinct from eachother"
- I move focus to the "Simple terms" menu item, the hover colour is now removed from "Distinct from eachother"

**Comment by alex-page** [comment]
@rhubarbselleven I am going to close this issue as I can't replicate it. If you can provide steps happy to re open the issue.
