### ISSUE TITLE
select triangles show with custom color scheme 

### ISSUE THREAD

**Issue by KiriHoy** [govau/design-system-components#604]
# Bug Report

- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/design-system-components/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/design-system-components/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened
I customised the colors and the select box triangles showed in Google Chrome

## Reproducing

- Module name: select 
- Module version: 2.0.9

Steps to reproduce:

1. customise action color
2. use latest version of Chrome

## Attachments
![capture](https://user-images.githubusercontent.com/34221033/51712174-0e580e80-2082-11e9-82fa-2ea4b8fe53ee.PNG)

**Comment by alex-page** [comment]
Thanks @KiriHoy!

This may be an issue related to how `sass` -> `css` is built. When I use the `pancake.min.css` file from the design system I can not replicate the issue. However if I build the `sass` -> `css` with only `node-sass` I can repeat this error.

I would recommend making sure you have `autoprefixer` installed and have a script running like [these examples](https://designsystem.gov.au/get-started/development-environment/#scripts). I noticed our documentation is missing the [`browserlist`](https://github.com/govau/design-system-site/blob/738e4c3b4a08dd1e7e82bc6fca809799e553a2a7/package.json#L149-L154) so I have [made an issue](https://github.com/govau/design-system-site/issues/407) to fix that up.

 Let me know if that fixes the issue 👍
