### ISSUE TITLE
VueJS support 

### ISSUE THREAD

**Issue by geethab** [govau/design-system-components#621]
Kudos to the component library. Great effort.

## How can we help?

Any support for using these components with VueJS? 

## What you have tried:

I tried importing the AUButton and using them the same way with VueJS but it errored out looking for react js files.

**Comment by adamzerella** [comment]
Hey @geethab! As of right now, our components only support the [React](https://reactjs.org/) framework. We always like to keep the floor open when it comes to supporting other frameworks but we don't currently have the resources to support other stacks.

If you prefer not to use React, that's totally cool - This design system will work just fine without it, using just the bundled `CSS` styling and `HTML` markup like the examples seen here: https://designsystem.gov.au/components/buttons/#default

To grab the bundled CSS and start styling away 💃check out: https://designsystem.gov.au/download/
