### ISSUE TITLE
Utility classes

### ISSUE THREAD

**Issue by HurricaneInteractive** [govau/design-system-components#671]
# Support question

- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/design-system-components/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues/questions on github
- [x]  I've searched the [community forums](https://community.digital.gov.au/c/designsystem) to check for related issues or support questions

## How can we help?

I am wondering if there is documentation around for "utility" classes. Classes that applies a clearfix or sets the transform of text to uppercase, lowercase etc. Something similar to the bootstrap [helper classes](https://getbootstrap.com/docs/3.3/css/#helper-classes)

**Comment by sukhrajghuman** [comment]
Hey @HurricaneInteractive thanks for bringing this up!

I would look into our [core module documentation](https://designsystem.gov.au/components/core/code/). 

We don't have text transform classes. But there is a sass mixin to [apply a clearfix](https://designsystem.gov.au/components/core/code/#au-clearfix).

Does that answer your question?

**Comment by HurricaneInteractive** [comment]
@sukhrajghuman thanks! That answers my question.

**Comment by sukhrajghuman** [comment]
No problem. If anything else pops up feel free to reach out any time :)
