### ISSUE TITLE
Test branch deployments should get deleted after branch is deleted

### ISSUE THREAD

**Issue by sukhrajghuman** [govau/design-system-components#678]
# Bug Report

- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/design-system-components/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/design-system-components/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

When we add a `-test` to the end of a branch name, the branch is automatically deployed. However, once we delete that branch, the deployments still exist. I wonder if we can automatically delete these deployments, once the branch is deleted?

For example: these exist, but the branches have been deleted

design-system-components-featureexplicit-label-test.apps.y.cld.gov.au
design-system-components-featureexplicit-labels-2-test.apps.y.cld.gov.au
designsystem-featureroadmap-test.apps.y.cld.gov.au

**Comment by adamzerella** [comment]
After some quick research there really isn't a simple way to do this. The easiest way is probably to run a script with a CircleCI cron task: https://circleci.com/docs/2.0/configuration-reference/#cron

**Comment by sukhrajghuman** [comment]
I've got access to cf spaces so I can just remove these deployments every couple of weeks

**Comment by adamzerella** [comment]
Nice

**Comment by sukhrajghuman** [comment]
yea easy solution for now...
