### ISSUE TITLE
Add number react prop for text-inputs

### ISSUE THREAD

**Issue by sukhrajghuman** [govau/design-system-components#695]
# Feature Request
- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/design-system-components/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/design-system-components/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.
- [x] I've searched the [community forums](https://community.digital.gov.au/c/designsystem) to check for related issues or feature requests

Our text inputs should have a `number` prop to add the `au-text-input--number` class. This is probably cleaner adding the `au-text-input--number` via the className prop. The defaultProp value for this prop would be `false`

![image](https://user-images.githubusercontent.com/20184809/54727258-ed67f180-4bca-11e9-8d84-eb801feade50.png)

**Comment by gordjw** [comment]
@sukhrajghuman you'll need to add support for the min, max and step properties at the same time (if you haven't got them already).

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#Allowing_decimal_values

**Comment by sukhrajghuman** [comment]
@gordjw 

The only reason for adding the `number` prop was so that the `AUtextInput` react component will inherit styling as defined per the `au-text-input--number` class.

So <AUtextInput number={true} /> will render something like this

![image](https://user-images.githubusercontent.com/20184809/55772458-a7b68e80-5acf-11e9-8eb5-c2a6b9be6554.png)

as opposed to <AUtextInput number={false} />, which will render something like this:

![image](https://user-images.githubusercontent.com/20184809/55772466-b13ff680-5acf-11e9-880b-7f89a6f1c438.png)

The min, max and step properties will not add any styling, and can be added without a react prop, so they are unneccessary in this case. I will make my issue description a bit more clear 😅

**Comment by gordjw** [comment]
No, that's my bad @sukhrajghuman. I forgot that React passes through props by default, disregard :)
