### ISSUE TITLE
helper.js add check package.json existence before require

### ISSUE THREAD

**Issue by toxamiz** [govau/design-system-components#696]
# Bug Report

- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/design-system-components/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/design-system-components/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

Some folders and files like `lib`, `node_modules` in package folder are in `.gitignore`, so when you switch branches these folders stays on place. When you collect folders(e.g. modules) for further usage these "empty" module also gets into result. This provides an error when you try to require `package.json` from it.

```
Error: Cannot find module '/var/www/github/design-system-components/packages/file-upload/package.json'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.json (/var/www/github/design-system-components/scripts/helper.js:642:26)
    at Object.init (/var/www/github/design-system-components/scripts/helper.js:625:20)
    at Object.HELPER.init (/var/www/github/design-system-components/scripts/helper.js:1233:19)
    at Object.<anonymous> (/var/www/github/design-system-components/scripts/helper.js:1254:8)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)

```

## What I expected to happen

No error :)

## Reproducing

- Module name: scripts/helper.js

Steps to reproduce:

1. Checkout new branch
2. Init, build and commit new component 
2. Switch back
3. `cd` into the any existing package folder
4. run `npm run watch`

**Comment by adamzerella** [comment]
@toxamiz I've left some feedback in #697 but I admit that I don't think I fully understand what you are talking about? `lib/` and `node_modules/` certainly have a place in the `.gitignore` like you mention but your referring to references to ignored components not updating?

**Comment by toxamiz** [comment]
You can follow steps to reproduce.

I have a branch with new component and some commits. Then i switch to `develop`.  Git updates files to this state, so files from my component no longer presents. But files from `.gitignore` stays in place.

```
// my branch

my-component
- lib
- node_modules
- tests
- src
package.json
...other

// switch to develop, these folders stays in place

my-component
- lib
- node_modules
- tests
```

In helper.js you collect all `folders`, and then require package.json from each. But in my-component  `package.json`doesn't exists, it is in other branch. Folder exists, `package.json` - not. That causes an error.

**Comment by adamzerella** [comment]
This is expected behaviour? When switching from a branch with a new component to something like `develop`, the files will be ignored as they are not on the targeted branch...

I would suggest looking at options like `git stash`, see: https://git-scm.com/docs/git-stash when switching between branches and commits
