### ISSUE TITLE
aria-label="main navigation" causes repetition

### ISSUE THREAD

**Issue by electronicwoft** [govau/design-system-components#703]
the ARIA navigation role is a named role such that the word 'navigation' is included in the announcement of the role information for screen readers. Providing an accessible name that repeats the type of role is unnecessary for named roles and causes irritating repetition. for example:
<div role="navigation" aria-label="main navigation"> is announced as 'main navigation navigation region'.

**Comment by sukhrajghuman** [comment]
hey @electronicwoft really appreciate bringing this up. 

I think the reasoning behind this was to distinguish the `<nav>` in the main nav from a `<footer>` with a `<nav>` element.

We also use `aria-label="footer navigation"` for the `<nav>` inside the footer component. 

Do you think that is a valid reason, or do you think it causes more harm than good?

I can see how this can be frustrating for screen reader users. I will check with the accessibility team.

**Comment by electronicwoft** [comment]
remove the word 'navigation' from both of these aria-labels and all will be resolved ... `<nav aria-label="footer">` and `<nav aria-label="main">`

**Comment by KiriHoy** [comment]
Hi all . I've done some testing. 

With the current main navigation:
```html
<nav class="au-main-nav" aria-label="main navigation">
 
</nav>
```
**VoiceOver + Safari**

> "main navigation navigation"

**NVDA + Edge** 

> "main navigation grouping list"

<hr>

After removing the word 'navigation' from the `aria-label`, like so:

```html
<nav class="au-main-nav" aria-label="main">
 
</nav>
```
Using **VoiceOver and  Safari**, I get the following reading:

> "main, navigation"

Using **NVDA and Edge**

> "main grouping list"

**Comment by electronicwoft** [comment]
I'm interested in the rationale for the user agent combinations used for testing ... but glad to see that IE didn't make it onto the list!

**Comment by sukhrajghuman** [comment]
@electronicwoft you ask, we deliver 😉 

**IE11 + NVDA + current main nav**

```html
<nav class="au-main-nav" aria-label="main navigation">
```

**Reads out**
> "main navigation, navigation landmark list with 8 items, ..."

<hr />

**IE11 + NVDA + suggested main nav**
```html
<nav class="au-main-nav" aria-label="main">
```
> "main, navigation landmark list with 8 items, ..."


In terms of screen readers, we try testing all of our components with voice-over, NVDA and JAWS. Right we are currently in the process of renewing our JAWS license, so don't have access to that.

There are some screen readers we don't have access to, so we rely on community feedback to let us know of those situations, and amend our code accordingly. As an example, the way we marked up our checkbox/radio inputs [was not being read out correctly](https://github.com/govau/design-system-components/issues/597) by the Dragon screen reader.  After this we changed markup (making sure it didn't affect semantics/usability/other screen readers etc.).

**Comment by electronicwoft** [comment]
I was wondering where JAWS was ... this is an implementation issue rather than an accessibility support issue, but nice work on the testing ...how about Android Accessibility Suite and Voiceover for IOS? There's a Dragon screen reader? While we're on the topic, would the DTA ever publish an accessibility support baseline?

**Comment by sukhrajghuman** [comment]
yeah it is, but it's always good to test. In this case we found that the current markup works well with Edge, but not other browsers.

Still it's probably better to remove the `navigation` word from the `aria-label`. I believe all components are tested in mobile screen readers too before being published. 
I'd have to check with the accessibility team with regards to the support baseline.

**Comment by electronicwoft** [comment]
... and then retest when Edge becomes chromium (and more accessible) later in the year?

**Comment by sukhrajghuman** [comment]
Any reason for closing the issue? I think it's still valid. There doesn't seem to 'one size fits all' solution in terms of how browsers are reading it, however removing the word `navigation` from the `aria-label` seems to be better solution for **most** browsers. I'm still in favour of it. I have a meeting with the accessibility team tomorrow and wanted to get their opinion. Will post findings and best course of action here.

**Comment by electronicwoft** [comment]
sorry! must have pressed the comment and close button ... But there IS a one-size-fits-all-solution and that's to remove the word 'navigation' from the accessible name for `<nav>` elements or elements that host the role='navigation' attribute. I'd completely ignore the results from Microsoft Edge because 'main navigation grouping list' is nonsense anyway.

**Comment by sukhrajghuman** [comment]
@electronicwoft the accessibility team concur. Will remove this 'navigation' from both the main nav and footer components :)

**Comment by sukhrajghuman** [comment]
Docs will be updated shortly. Follow this: https://github.com/govau/design-system-site/issues/506

**Comment by electronicwoft** [comment]
thanks @sukhrajghuman and @KiriHoy -  love your work. stay tuned for more!
