### ISSUE TITLE
npm readme instructions have `--save-dev`

### ISSUE THREAD

**Issue by sukhrajghuman** [govau/design-system-components#718]
In the components for our `npm` pages the instrcutions have the `--save-dev` flag. 

![image](https://user-images.githubusercontent.com/20184809/55508253-3cbb2100-56a5-11e9-953d-8a2d1aad48ea.png)

The `--save-dev` flag should not be there. The components are not dev dependencies.

**Comment by AmanDeep9925** [comment]
Does someone is working on this issue, or could i just take it by myself.

**Comment by AmanDeep9925** [comment]
> In the components for our `npm` pages the instrcutions have the `--save-dev` flag.
> 
> ![image](https://user-images.githubusercontent.com/20184809/55508253-3cbb2100-56a5-11e9-953d-8a2d1aad48ea.png)
> 
> The `--save-dev` flag should not be there. The components are not dev dependencies.

This issue have been solved on the same day.
