### ISSUE TITLE
Backgrounds (e.g. Google Maps) are not printed

### ISSUE THREAD

**Issue by jcc-a** [govau/design-system-components#744]
# Bug Report

- [x] I’ve read and understood the [Contributing guidelines](https://github.com/govau/design-system-components/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/design-system-components/blob/master/CODE_OF_CONDUCT.md).
- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

Background images are not printed. Google Maps content does not print.

## What I expected to happen

Background images are printed. Google Maps are printed.

- Module name: @gov.au/body, @gov.au/responsive-media

1. Create basic HTML page
2. Add @gov.au/body as a dependency
3. Add resulting pancake.min.css to HTML
4. Add simple Google Maps API script to HTML
5. Visit HTML page and print the page

## Attachments

Screenshots for web view and printed view:
https://drive.google.com/open?id=1LxZpZImetOIphlzn2_1b72eFk4SK4h81

## Questions / Notes

**Can the `background: #fff !important;` be changed to `background: transparent !important`?**

https://github.com/govau/design-system-components/blob/b4dcf82337c848eddd2a63f10b5b39ec997bfb04/packages/body/src/sass/_print.scss#L10-L20

This behaviour can be overridden to work as expected:

```css
background: transparent !important;
```

As this is site-wide CSS, it is tedious undoing this rule when dealing with third-party widgets.  Refer to MDN for opinions / rules of thumb,: [The !important exception](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#The_!important_exception)

Enforcing `background: #transparent` and `color: #000` in print styles is often done to save ink and ensure contrast when printing. A related discussion: https://github.com/h5bp/html5-boilerplate/issues/1643

As an alternative, the `background` and `color` print overrides might be removed completely.

Some potential side effects / issues caused by removing the background\color overrides:

- Colour filled backgrounds and coloured text will be coloured when printed.
- It may be difficult to read printed web pages when there is a lack of contrast between background and foreground
- More ink is used?
- The page is printed true to the content viewed in the web browser

**Comment by adamzerella** [comment]
I'm not able to replicate this problem @jcc-a? I followed the reproduction steps and my embedded Google Map prints correctly?

I'm embedding the map as an `iframe` like so:

```js
<body>
    <main class="au-body">
        <section>
            <h1>Body: test</h1>
        </section>
        <section>
            <iframe width="600" height="450" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/view?zoom=9&center=-34.9285%2C138.6007&key=..." allowfullscreen></iframe>
        </section>
    </main>
</body>
```

Which prints as: 

![image](https://user-images.githubusercontent.com/1501560/56940960-be8f5480-6b54-11e9-8df2-088354857a03.png)

I don't think changing the default background color from `#fff` to `transparent` is the right solution here

**Comment by jcc-a** [comment]
Thanks for taking a look at this @adamzerella. I've made a [reproduction](https://jcc-a.github.io/bug--govau-design-system-components--body/index.html) of this issue. 

On the map, hit OK for the **This page can't load Google Maps correctly.** and ignore the **Development purposes only** watermark. Google is now enforcing API keys and billing for Google Maps API.

The bug described above is specific to [Google Maps API](https://developers.google.com/maps/documentation/javascript/examples/map-simple).

**Comment by adamzerella** [comment]
Thanks for clarifying @jcc-a, after a bit more testing I see what you mean now. We'll patch `body` to print with `background-color: transparent !important;` instead of `#fff` 👍 

Working PR: #750
