### ISSUE TITLE
Numeric table cell should be using monospace font

### ISSUE THREAD

**Issue by sukhrajghuman** [govau/design-system-components#758]
The numeric table cells should be using monospaced fonts to make it easier to compare numbers

![image](https://user-images.githubusercontent.com/20184809/57597940-abd54080-7594-11e9-9431-4b13425e8e33.png)

VS

![image](https://user-images.githubusercontent.com/20184809/57597916-9bbd6100-7594-11e9-8a40-0543ddb0e5ab.png)

**Comment by gordongrace** [comment]
I'd consider putting these examples up against those recommended by the _Style manual (6th Ed.)_ :

**Comment by sukhrajghuman** [comment]
From the [Content Guide](https://guides.service.gov.au/content-guide/numbers-measurements/#numbers)

>Add a comma between the third and fourth digit from the right, for numbers 10,000 and above.'


Style manual, page 176

>In tables or other layouts where the vertical alignment of digits is important for the purpose of comparison or computation, use a thin space for internal divisions of larger numerals.
For example:
10 141
--1 721
---253


The numbers are monospaced though
