### ISSUE TITLE
Table numbers font is not as expected (system SF)

### ISSUE THREAD

**Issue by sirleech** [govau/design-system-components#776]
# Bug Report

- [x ] I’ve read and understood the [Contributing guidelines](https://github.com/govau/design-system-components/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [ x] I’ve read and agree to the [Code of Conduct](https://github.com/govau/design-system-components/blob/master/CODE_OF_CONDUCT.md).
- [x ] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

Table numbers font seems to be Verdana, not the system font as expected.

## What I expected to happen

On a mac, I expect this to be the SF system font. It looks a bit broken being in Verdana.

## Reproducing

Latest, as on the documentation page

## Attachments

<img width="328" alt="Screen Shot 2019-05-28 at 8 54 17 am" src="https://user-images.githubusercontent.com/680844/58441552-376ad780-8126-11e9-8c69-f6be6ee344ed.png">
<img width="705" alt="Screen Shot 2019-05-28 at 8 54 21 am" src="https://user-images.githubusercontent.com/680844/58441553-376ad780-8126-11e9-9cd9-bc0516893fb2.png">

**Comment by sukhrajghuman** [comment]
@sirleech yeah we are still trying to figure this out. If we used the default numeric (monospace) family it would look like this, which I thought looked a bit odd.

![image](https://user-images.githubusercontent.com/20184809/58441773-0e4b4680-8128-11e9-9550-7d5a8607c5a0.png)

I was looking for a web safe font that has monospacing for numbers, but not other characters such as commas, decimals etc. I came across Verdana and it looked okay. But I think it makes sense to revert back to our monospace font family.

What are your thoughts?

**Comment by sirleech** [comment]
Makes sense Raj— this should not be a bug then as it was deliberate, feel free to close.

**Comment by sukhrajghuman** [comment]
@sirleech I'll leave it open for now, in case anybody has an elegant solution to this problem.

**Comment by sirleech** [comment]
This seems to work ok:
`font-variant-numeric: tabular-nums;`

![image](https://user-images.githubusercontent.com/680844/58443446-42793400-8135-11e9-9b95-18259fd7d9ec.png)

**Comment by sukhrajghuman** [comment]
@sirleech I think you are onto something, let me give this a whirl 👍

**Comment by sukhrajghuman** [comment]
okay cool so `font-variant-numeric` is not supported on older browsers...but I can use `font-variant:` and apply this property to the `.au-table__cell--numeric` class. Thanks Chris!
