### ISSUE TITLE
Images on card overflow the border radius

### ISSUE THREAD

**Issue by petrillek** [govau/design-system-components#859]
# Bug Report

- [X] I’ve read and understood the [Contributing guidelines](https://github.com/govau/design-system-components/blob/master/CONTRIBUTING.md) and have done my best effort to follow them.
- [X] I’ve read and agree to the [Code of Conduct](https://github.com/govau/design-system-components/blob/master/CODE_OF_CONDUCT.md).
- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

Images in basic Cards (no shadow) are overlapping over the border radius.

## What I expected to happen

Images should follow the same border radius.

## Reproducing

- Module name: Card
- Module version: 0.3.1
- Pancake version: 1.4.1
- Node version: 8.15.1
- npm version: 6.5.0
- Pancake settings in your `package.json`: Not related to the issue.

Steps to reproduce:

1. Go to https://designsystem.gov.au/components/card/#images
2. Compare with https://designsystem.gov.au/components/card/#images
3. Clickable Card has a class `au-card--shadow` which is setting property overflow: hidden; This property should be directly on the `au-card` class, so it will work on images even without shadow.

## Attachments

Styling was changed in the browser to better show the problem (bigger border raidus, different border color).

![card-image-overflow](https://user-images.githubusercontent.com/5556405/62064787-e5315a00-b22d-11e9-9ec7-0303dca5b587.png)

**Comment by sukhrajghuman** [comment]
@petrillek really nice pickup. Will correct it shortly
