### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by qfz** [govau/design-system-components#906]
There has been no commits since Jan and a bunch of PR's are waiting to be actioned. What's the status of this project?

**Comment by svict4** [comment]
Can't speak for them: but not really, it's a matter of priority and internal resourcing at DTA at the moment.

There are still plenty of new greenfield gov projects using the designsystem. Some are at a state level, such as https://www.covid19.qld.gov.au/ or have been forked and actively maintained, such as https://github.com/healthgovau/health-design-system

Come and say hello over on the forums https://community.digital.gov.au/c/designsystem/14 or on the slack https://guides.service.gov.au/join-slack/ and you might get a couple of people responding :slightly_smiling_face:

**Comment by rossmullen** [comment]
> There has been no commits since Jan and a bunch of PR's are waiting to be actioned. What's the status of this project?

Hi @qfz  The repos are still being maintained. I'm the UX Engineer on the project in a small team and we're currently working through the outstanding PR's. We've fixed a few issues and closed off several PR's. We're also looking at improving our a11y process and enhancing the documentation for getting started.
