### ISSUE TITLE
'unsafe-eval' for strict CSP policy headers

### ISSUE THREAD

**Issue by kozillla** [govau/design-system-components#933]
Hi Guys,

I am trying to use the animate package on the website where I'm setting up Content Security Policy headers, sadly it fails due to 'unsafe-eval' check. 

It is caused by : 
https://github.com/govau/design-system-components/blob/cc5cb0e693b4350061159bdbc15252d99c34aa42/packages/animate/src/js/module.js#L343

Is it any reason why eval is used here? It would be a minor change to ```exports.default = AU```  
I am happy to create PR if require.

**Comment by gordjw** [comment]
Thanks for reporting @kozillla, change appears logical and tests are passing.
Will push this into production asap.
